opentelemetry-collector:
  # Valid values are "daemonset", "deployment", and "statefulset".
  mode: "deployment"

  image:
    # If you want to use the core image `otel/opentelemetry-collector`, you also need to change `command.name` value to `otelcol`.
    repository: "otel/opentelemetry-collector-contrib"

security:
  password: "changeme"
  networkPolicy:
    enabled: false
    from: []
  allowlist:
    enabled: false
    ip: "0.0.0.0/0"

networking:
  type: ClusterIP
  clusterIP: None
  service:
    port: 8088
  user:
    enabled: false
    port: 5000

ingress:
  enabled: false
  tls: true
  ingressClassName: ""
  annotations:
    []
    # kubernetes.io/tls-acme: "true"
  hostname: chart-example.local
  userHostname: chart-example-user.local
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
  useCertManager: false
  certManagerClusterIssuer: ""

route:
  enabled: false
  annotations:
    []
    # route.openshift.io/termination: "reencrypt"
  hostname: chart-example.local
  userHostname: chart-example-user.local
  tls:
    termination: edge
    # key:
    # certificate:
    # caCertificate:
    # destinationCACertificate:
  wildcardPolicy: None

userPreferences:
  language: "en"
